store_categories = {
    'BYU DES:MFC eCheck': 'Other',
    'TARGET': 'Shopping',
    'WM SUPERCENTER': 'Groceries',
    'Deseret Book': 'Books Music',
    'SMITHS FOOD': 'Groceries',
    'SMITHS FUEL': 'Gas',
    '7 ELEVEN': 'Gas',
    'MAVERIK': 'Gas',
    'SQ THE NUT FATHER': 'Food Snacks',
    'SHELL OIL': 'Gas',
    'UTAH DMV OFFICES': 'Car',
    'UTAH TRANSIT AUTHORITY': 'Transportation',
    'BYU WSC COUGAR EXPRESS': 'Food Snacks',
    'SQ BROOKERS FOUNDING FL': 'Food Snacks',
    'STRANGLING BROTHERS CIRC': 'Entertainment',
    'IN N OUT': 'Fast Food',
    'BUN MEE': 'Fast Food',
    'SLC AIRPORT PARKING': 'Transportation',
    'ARCO': 'Gas',
    'SAINT MARYS COLLEGE': 'Education',
    'UNITED': 'Airline',
    'BOUDIN BAKERY': 'Fast Food',
    'LAZ PKG': 'Parking',
    'TST Millies American Ki': 'Food Snacks',
    'LAFAYETTE RES METER PARK': 'Parking',
    'THE RANCH HOUSE CAFE': 'Food Snacks',
    'SQ YOGURT SHACK': 'Food Snacks',
    'CHICK FIL A': 'Fast Food',
    'STARBUCKS STORE': 'Fast Food',
    'PANDA EXPRESS': 'Fast Food',
    'AIR STOP': 'Transportation',
    'AMERICAN AIR': 'Airline',
    'ALLIANZ TRAVEL INS': 'Insurance',
    'CMSVENDT B VENDING': 'Food Snacks',
    'CAFE ZUPAS': 'Fast Food',
    'SQ GETOUT GAMES': 'Entertainment',
    'SQ CHOM BURGER': 'Fast Food',
    'THE HOME DEPOT': 'Home Improvement',
    'SUPER CHIX CHICKEN': 'Fast Food',
    'FREEDOM CAR WASH': 'Car Wash',
    'COSTA VIDA': 'Fast Food',
    'MUCHAS GRACIAS MEXICAN FO': 'Fast Food',
    "MCDONALD'S": 'Fast Food',
    'CAFE RIO': 'Fast Food',
    'CHIPOTLE' : 'Fast Food',
    'WAL MART' : 'Groceries',
    'FANDANGO' : 'Entertainment',
    'Amazon' : 'Shopping',
    'AMZN' : 'Shopping',
    'DAIRY QUEEN' : 'Fast Food',
    'ALOHA PLATE' : 'Fast Food',
    'FUEL' : 'Gas',
    'QuestarGas' : 'Utilities-Gas',
    'UTAH FIRST CU' : 'Car Payment',
    'BRIGHAM YOUNG UN DES:DIR DEP' : 'TA',
    'VENMO DES:CASHOUT' : 'Venmo Deposit',
    'VENMO DES:PAYMENT' : 'Venmo Payment',
    'Ch JesusChrist DES:DONATION' : 'Tithing',
    'GUSTO DES:PAY' : 'MarketDial',
    'BYU VENDING' : 'Food Snacks',
    'TRADER JOE S' : 'Groceries',
    'GOOGLE DES' : 'Wifi',
    'The Quarry DES': 'Gym',
    "BROOKER'S FOUNDING FL" : 'Food - Desserts',
    'SALT & STRAW ICE CREA' : 'Food - Desserts',
    'YOGURT SHACK' : 'Food - Desserts',
    'AMAZON.COM' : 'Shopping',
    'PROVO CITY UTILI DES' : 'Utilities',
    'TURO INC.' : 'Travel',
    'SCERA' : 'Entertainment',
    'TACO BELL' : 'Fast Food',
    'CHOICES' : 'Fast Food',
    'CHEVRON' : 'Gas',
    'BYU STORE' : 'Shopping',
    'MTC VENDING PROVO' : 'Food Snacks',
    'Online Banking payment to CRD' : 'Credit Card Payment',
    'Online Banking transfer' : 'Transfer',
    'Check' : "Rent",
    'Online payment from CHK' : 'Credit Card Payment',
    'USU MOBILESTUDENTEVENT goo.gl/gVdePhU' : 'Entertainment',
    'The Cleaning Solution' : 'Laundry',
    'Millies American Ki' : 'Restraunt Food',
    'Bank of America Credit Card Bill Payment' : "Credit Card Payment",
    'JIFFY LUBE': "Car",

}

overall_categories = {
    'Food': 'Food',
    'Utilities': 'Utilities',
    'Convenience Store' : 'Food',
    'Books Music': 'Shopping',
    'Shopping': 'Shopping',
    'TA' : 'Income',
    'MarketDial' : 'Income',
    'Venmo Deposit' : 'Income',
}